### ISSUE TITLE
Can't install CLI on MacOs Ventura v 13.0.1

### ISSUE THREAD

**Issue by JTXFive** [bigcommerce/stencil-cli#1039]
### Expected behavior

Successful installation

### Actual behavior

failed to install

### Steps to reproduce behavior

npm install -g @bigcommerce/stencil-cli

### Environment

Stencil-cli version `stencil --version`:

None - can't install

Node version `node -v`:

6.14.17

NPM version `npm -v`:

v14.20.0

OS:

MacOs Ventura v 13.0.1

###Error given

`gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jt/.nvm/versions/node/v14.20.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-sass/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 22.1.0
gyp ERR! command "/Users/jt/.nvm/versions/node/v14.20.0/bin/node" "/Users/jt/.nvm/versions/node/v14.20.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/jt/.nvm/versions/node/v14.20.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-sass
gyp ERR! node -v v14.20.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@6.0.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@6.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jt/.npm/_logs/2022-12-08T15_20_38_513Z-debug.log`

Followed all instructions (opening in Rosetta mode etc), tried with node v14.20 and even v15, but the installation always fails.
Can't seem to find what could be the problem.

**Comment by robincoferbc** [comment]
Hi @JTXFive, please note that currently Node versions 16.x and 18.x are supported with Stencil CLI. In addition, as can be seen in the package.json file here:
https://github.com/bigcommerce/stencil-cli/blob/master/package.json
The npm version must be ">=8.0.0 <10.0.0".
