### ISSUE TITLE
Stencil CLI fails to load and hangs when trying to use a modified Elevate Stencil theme

### ISSUE THREAD

**Issue by jwboykinUC** [bigcommerce/stencil-cli#1046]
### Expected behavior
Stencil cli starts upon executing stencil start command
### Actual behavior
Error: Cannot find module 'webpack-merge'
Require stack:
- C:\path\to\folder\webpack.dev.js
- C:\path\to\folder\stencil.conf.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\users\johnw\downloads\PM+Four+Banners+Top+Banner-1.5.0\webpack.dev.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '- C:\\path\to\\folder\\webpack.dev.js',
    '- C:\\path\to\\folder\\stencil.conf.js'
  ]
}
### Steps to reproduce behavior
Fresh install of Chocolatey, Stencil CLI, Windows C++ Build Tools, and Python2 as per instructions inside BigCommerce Dev Center
### Environment

Stencil-cli version `stencil --version`:

Node version `node -v`: 14.20.0

NPM version `npm -v`: 6.14.17

OS: Windows 10

**Comment by jwboykinUC** [comment]
Found a way to resolve this.  The following packages needed to be installed seperately via npm:
webpack-bundle-analyzer
clean-webpack-plugin
lodash-webpack-plugin
babel-loader
jquery
