### ISSUE TITLE
Stencil-cli not fully working on Docker

### ISSUE THREAD

**Issue by HenkHui** [bigcommerce/stencil-cli#1054]
### Expected behavior

When running Stencil-cli in Docker the following URL's should work from the host machine (in case of default port 3000):
http://localhost:3000 -> BrowserSync "wrap"
http://localhost:3001 -> Server URL which is proxied by BrowserSync 
http://localhost:3002 -> BrowserSync UI

### Actual behavior

http://localhost:3001 is not available on host machine and therefore BrowserSync is not working. This is caused by the fact that the server is created with host "localhost" (instead of 0.0.0.0) and therefore not listening on all network interfaces.
Within the container the URL is working fine. The other URL's are are also working, so I can access the site through http://localhost:3000 and the BrowserSync  UI through http://localhost:3002.

### Steps to reproduce behavior

Run Stencil start in Docker environment and check whether the URL's which are mentioned in the output are working from the host machine:
[Browsersync] Proxying: http://localhost:3001
[Browsersync] Access URLs:
  Local: http://localhost:3000
  UI: http://localhost:3002

### Environment

Stencil-cli version `stencil --version`:
5.2.2 but also 
Node version `node -v`:
v14.19.1
NPM version `npm -v`:
6.14.16
OS:
Docker images node:14.19.1-alpine and also node:14 (Ubuntu)

**Comment by jairo-bc** [comment]
Hi @HenkHui, do you mind providing exact steps to reproduce with the commands you run into (or screenshots)? 
Thanks

**Comment by HenkHui** [comment]
Ok, so, I changed the way the server is initialized in the packages directory to see whether it actually fixes the "hot reloading" by changing these lines in "node_modules/@bigcommerce/stencil-cli/server/config.js

```
server: {  
    host: 'localhost',  
    port: 3000,  
},
```
to

```
server: {  
        host: '0.0.0.0',  
        port: 3000,  
    },
```

And this fixes the issue in which the proxied URL (http://localhost:3001/) cannot be reached from the host machine. However it did **not** fix the "hot reloading" issue in Docker. The browser still would not reload on file changes.

After some further inspection it looks like this is caused by an issue in Chokidar (which is used by BrowserSync) which doesn't seem to notice changes inside Docker mounted volumes.

See: https://github.com/paulmillr/chokidar/issues/1051

My workaround for now is to force Chokidar to use polling by setting some environment vars in my Docker Compose file:

```
   environment:  
      CHOKIDAR_USEPOLLING: true  
      CHOKIDAR_INTERVAL: 1000
```

NB: I need to set the interval as well (CHOKIDAR_INTERVAL) because the default value (300) causes some serious CPU load.

This certainly not ideal because the reloading is not "instant".

Any plans on allowing for other tooling in the Stencil CLI for "hot reloads", or at least a way to turn it off, so we can use some other tool/framework?

**Comment by sabotagebeats** [comment]
@HenkHui @jairo-bc is this the same issue? 

```
$ docker run -p 3000-3010:3000-3010 -v /$(pwd):/usr/src/app -it ghcr.io/bigcommerce/stencil-cli:lat
est stencil start
```
...
```
[Browsersync] Watching files...
node:events:502
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1908:16)
    at listenInCluster (node:net:1965:12)
    at Server.listen (node:net:2067:7)
    at Object.startServer [as fn] (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/browser-sync-ui/lib/async.js:123:39)
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/browser-sync-ui/lib/UI.js:185:14
    at iterate (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async-each-series/index.js:8:5)
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async-each-series/index.js:16:16
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/browser-sync-ui/lib/UI.js:193:13
    at Object.setUrlOptions [as fn] (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/browser-sync-ui/lib/async.js:76:9)
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/browser-sync-ui/lib/UI.js:185:14
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1944:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v20.20.2
```
