### ISSUE TITLE
node-sass is failing

### ISSUE THREAD

**Issue by hatzipanis** [bigcommerce/stencil-cli#253]
Running `npm install -g bigcommerce/stencil-cli` the build fails and I get the following error:

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/node-sass
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bigcommerce/stencil-cli"
npm ERR! node v6.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexhatzipanis/Sites/stihl/npm-debug.log
```

**Comment by dstaley** [comment]
@hatzipanis `stencil-cli` is only tested against node v4, and it looks like you're using v6.9.1. I can't guarantee that's the specific issue preventing node-sass from being built, but trying it out in v4 might be a good way to get up and running until v6 is supported. It looks like you're using OS X, so you might want to look into [nvm](https://github.com/creationix/nvm) if you want to keep v6 as your system node.

**Comment by jnorth** [comment]
I've had the same issue after recently upgrading to Node v6. Node v5.12 works fine though 👍

**Comment by hatzipanis** [comment]
That solved it! Thanks guys.

Really enjoying the Stencil experience, well done!
