### ISSUE TITLE
The BigCommerce server responded with a 500 error

### ISSUE THREAD

**Issue by hatzipanis** [bigcommerce/stencil-cli#255]
Weird. This was working fine for me this morning but now I'm getting: 

```
Debug: internal, implementation, error
    Error: Error: The BigCommerce server responded with a 500 error
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:44:31
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:135:20
    at finish (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:137:20)
    at wrapped (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/hoek/lib/index.js:866:20)
    at ClientRequest.onResponse (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:158:20)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
```

**Comment by hatzipanis** [comment]
A bit more info:

- Production site is working fine
- `stencil start` starts without problems
- Local version was working earlier this morning. I was editing templates when it returned the above error. Thought it might have been the changes so reverted but this hasn't fixed it
- Tried re-issuing token, no luck
- Site is currently in trial mode (which was extended for me)

**Comment by mcampa** [comment]
Hi @hatzipanis, we were having issues with one of our servers. Please try again, it should be solved now. 

Thank you for reporting

**Comment by hatzipanis** [comment]
Fixed. Cheers Mario!
