### ISSUE TITLE
stencil bundle Error

### ISSUE THREAD

**Issue by wizardmadness** [bigcommerce/stencil-cli#311]
stencil bundle
Password:
Validating theme...
Running ESLint...
/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^

Error: Cannot find module 'eslint-config-airbnb/base'
Referenced from: /usr/local/cornerstone/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config/config-file.js:479:33)
    at load (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config/config-file.js:496:24)
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config/config-file.js:530:22)
    at loadConfig (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/eslint/lib/config.js:227:22)

**Comment by mcampa** [comment]
Please upgrade you cli

```
npm i -g @bigcommerce/stencil-cli
```

**Comment by wizardmadness** [comment]
thank you
