### ISSUE TITLE
concat helper returns a SafeString, which can't be used in other helpers

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#320]
I am trying to use the `concat` helper to look up a value in the `theme_settings` object using the `get` helper. However, it looks like the `concat` helper returns a `SafeString`, which does not have a `split` method needed by the `get` helper.

For example, on a category page, I use the following block to lookup the current category and see if it exists in the `theme_settings.category_data` object:

```
{{#with (get (concat 'theme_settings.category_data.' category.id) this)}}
  {{log this}}
{{else}}
  <h1 class="pageHeading">{{category.name}}</h1>
{{/with}}
```

This results in the following error:

```
Debug: internal, implementation, error
    TypeError: Uncaught error: prop.split is not a function
    at Function.module.exports (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/node_modules/handlebars-helpers/node_modules/get-value/index.js:26:19)
    at Object.helpers.get (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/node_modules/handlebars-helpers/lib/object.js:137:19)
    at Object.template.main (eval at <anonymous> (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:40), <anonymous>:15:96)
    at ret (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at Object.invokePartial (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)
    at Object.invokePartialWrapper [as invokePartial] (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.template.6 (eval at <anonymous> (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:40), <anonymous>:26:23)
    at prog (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at Object.<anonymous> (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/helpers/block.js:9:16)
    at Object.template.main (eval at <anonymous> (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:40), <anonymous>:9:72)
```
I think this is because `concat` is returning a `SafeString`, which doesn't have a `split` method. Is it possible for the `concat` helper to return a regular string so it can be used to another helper?

**Comment by flyingL123** [comment]
Just discovered the `toPath` helper. I think this solves the problem.
