### ISSUE TITLE
stencil bundle outputs unhanded rejection errors, zips the files, but all js compilation fails

### ISSUE THREAD

**Issue by jesseconnr** [bigcommerce/stencil-cli#336]
I upgraded webpack and related configs based on the latest released cornerstone project. When I compile using webpack directly everything works as intended without any errors. However if I run `stencil bundle` it produces the output below and all javascript fails to compile. Considering webpack succeeds outside of bundle I'm having a hard time tracking down what is causing it so that I can reproduce it.

```
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Generating Manifest Started...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Manifest Generation Finished
ok -- Theme Schema Building Finished
Potentially unhandled rejection [4] TypeError: Cannot read property 'default' of undefined
    at d:\user\dev\project\site\node_modules\loader-runner\lib\loadLoader.js:4:66
    at tryCatchReject (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Potentially unhandled rejection [5] TypeError: Cannot read property 'default' of undefined
    at d:\user\dev\project\site\node_modules\loader-runner\lib\loadLoader.js:4:66
    at tryCatchReject (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Potentially unhandled rejection [6] TypeError: Cannot read property 'default' of undefined
    at d:\user\dev\project\site\node_modules\loader-runner\lib\loadLoader.js:4:66
    at tryCatchReject (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Potentially unhandled rejection [7] TypeError: Cannot read property 'default' of undefined
    at d:\user\dev\project\site\node_modules\loader-runner\lib\loadLoader.js:4:66
    at tryCatchReject (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Potentially unhandled rejection [8] TypeError: Cannot read property 'default' of undefined
    at d:\user\dev\project\site\node_modules\loader-runner\lib\loadLoader.js:4:66
    at tryCatchReject (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Potentially unhandled rejection [12] TypeError: Cannot read property 'default' of undefined
    at d:\user\dev\project\site\node_modules\loader-runner\lib\loadLoader.js:4:66
    at tryCatchReject (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Potentially unhandled rejection [16] TypeError: Cannot read property 'default' of undefined
    at d:\user\dev\project\site\node_modules\loader-runner\lib\loadLoader.js:4:66
    at tryCatchReject (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Users\user\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
ok -- Theme task Finished
ok -- SCSS Parsing Finished
ok -- Template Parsing Finished
ok -- Zipping Files Finished
Bundled saved to: d:\user\dev\project\site\Bases Loaded-1.5.10.zip
```

**Comment by jesseconnr** [comment]
I narrowed this down to jspm. Cleaned it out of stencil-bundle.js and everything works now.
