### ISSUE TITLE
Stencil Push isn't working

### ISSUE THREAD

**Issue by leonperez1870** [bigcommerce/stencil-cli#342]
I am trying to push some work that I did to a cornerstone theme. Everything works locally and bundles fine, but when I try to upload manually or through the terminal, it fails.

stencil push
_http_outgoing.js:487
    throw new Error('"value" required in setHeader("' + name + '", value)');
    ^

Error: "value" required in setHeader("x-auth-client", value)
    at validateHeader (_http_outgoing.js:487:11)
    at ClientRequest.setHeader (_http_outgoing.js:496:3)
    at new ClientRequest (_http_client.js:171:14)
    at Object.request (http.js:39:10)
    at Object.request (https.js:239:15)
    at internals.Client.request (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:178:24)
    at internals.Client._shortcut (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:579:16)
    at internals.Client._shortcutWrap (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:556:17)
    at internals.Client.get (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:521:17)
    at Object.getThemes (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/lib/theme-api-client.js:95:11)

I passed it on to another guy on my team and same issue. Everything ran fine locally but his error was as follows:

`Processing [======                                              ] 12%; ETA: 9.6snot ok -- JobCompletionStatusCheckError: Job Failed
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.`

So here I am...

**Comment by mcampa** [comment]
Can you make sure that your clientId is set in `.stencil` file?
if is not, re-run `stencil init` and enter your client id

**Comment by leonperez1870** [comment]
For some reason, it's only letting me use the Legacy API so I am using `"usermame":` and `"token":` in the stencil file

**Comment by mcampa** [comment]
`stencil push` only works with oauth tokens. You'll need to create oath credentials in your control panel.

**Comment by mcampa** [comment]
There might be an issue in your bundle that is caught server side and not by stencil-cli. Do you see any errors after you upload it?

**Comment by leonperez1870** [comment]
`Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Template Parsing Finished
(node:10509) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
ok -- Theme task Finished
Generating Manifest Started...
ok -- Manifest Generation Finished
ok -- Zipping Files Finished
Bundled saved to: /`

**Comment by leonperez1870** [comment]
Uploading the theme manually works, but when it is processing the theme I receive "There was a problem processing your theme"

**Comment by leonperez1870** [comment]
![screen shot 2017-09-21 at 2 39 49 pm](https://user-images.githubusercontent.com/8379344/30714255-22cdc6a4-9ee0-11e7-8c22-b4798800ae5f.png)

**Comment by leonperez1870** [comment]
![screen shot 2017-09-22 at 9 16 33 am](https://user-images.githubusercontent.com/8379344/30746160-cc454176-9f76-11e7-9389-1e4aaabf3f5d.png)

**Comment by mcampa** [comment]
Can you try to push a clean copy of Cornerstone to see if this is an issue with the store or your theme?

**Comment by leonperez1870** [comment]
@mcampa `not ok -- StoreHashReadError: Response Error: 503 Service Unavailable
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.`

**Comment by leonperez1870** [comment]
![screen shot 2017-09-25 at 9 45 48 am](https://user-images.githubusercontent.com/8379344/30811488-58aac62a-a1d6-11e7-99ae-82642393f2ef.png)

**Comment by leonperez1870** [comment]
It works with a clean version. Is there a log I can look at to see where the issue is?

**Comment by leonperez1870** [comment]
@mcampa I somehow managed to push the theme to the server. 

The way it worked:
I removed all the image files and did 'stencil push' leaving all the html and css I edited intact. It uploaded with no problems.
I dragged one picture to /img/ and it worked with no problems.
I dragged two pictures to /img/ and it crashed.
I had to add .png images one by one for it to work.

**Comment by mcampa** [comment]
That is weird. How big are the images?

**Comment by leonperez1870** [comment]
The biggest one was 5.1mb

**Comment by mjschock** [comment]
@leonperez1870 there's a 50mb limit that i'm guessing you reached with the images.  there was a similar issue closed here:  https://github.com/bigcommerce/stencil-cli/issues/344.  we have an internal ticket to fix the issue here:  https://jira.bigcommerce.com/browse/STENCIL-3959

**Comment by leonperez1870** [comment]
3 images did not equate to 50mb. They are 9,5,3 respectively.

**Comment by mjschock** [comment]
@leonperez1870 hmmm... if you run stencil bundle for the theme which doesn't upload successfully, how big is the zip?

**Comment by leonperez1870** [comment]
@mjschock Lol 24.4mb

**Comment by leonperez1870** [comment]
Btw the theme uploads fine now somehow. After I managed to upload the theme by placing the images one by one in the img folder, I added 3 more images and everything seems to work dandy.

**Comment by jbruni** [comment]
I guess the issue was weird image file **name** rather than file size.

**Comment by leonperez1870** [comment]
![screen shot 2017-11-03 at 4 17 51 pm](https://user-images.githubusercontent.com/8379344/32394193-ab105966-c0b2-11e7-9392-9221fbe1f9f7.png)
@jbruni What is wrong with using these file names?

**Comment by leonperez1870** [comment]
Litterally that's what I uploaded

**Comment by jermartin77** [comment]
I get the same issue. Total theme size is 28.8 mb. We have 7 large international sites that deploy via a script and it's failing both using the script which does a `stencil push` and manually doing a `stencil push` It's putting a much bigger strain on our deployment process, especially approaching the holidays. Some times it works. For example it failed on US, CA, but worked for France.

**Comment by jermartin77** [comment]
As a follow up, we've build a custom theme based on Cornerstone to start. If the issue boils down to file size. The largest culprits in the Cornerstone theme are some default images in the Cornerstone theme. I think BigCommerce could knock 4mb of the base theme size by optimizing these. 

![image](https://user-images.githubusercontent.com/1685645/48433916-8c6c7080-e735-11e8-81ef-4ca5c922dc97.png)

**Comment by brandonjp** [comment]
Having this same issue. 

`stencil push` gives this:
![PixelSnap 2019-10-29 at 11 04 15@2x](https://user-images.githubusercontent.com/199599/67786117-54406980-fa3c-11e9-842f-6043b1b415d8.png)

Manually uploading gives this:
![PixelSnap 2019-10-29 at 09 53 11@2x](https://user-images.githubusercontent.com/199599/67787332-5b687700-fa3e-11e9-9508-04445b4ed1a8.png)

I don't doubt that there might be an issue with my theme, but the only error info available implies it's a BigCommerce server issue: `A server error occurred`

**Comment by creativereason** [comment]
A year later I'm running into the same issue as well. Very frustrating that it isn't identifying the issue with the theme. Tried a couple different versions of CLI to see if it was something there and don't see any issues. Theme bundles fine, it dies halfway through the upload process. Uploading the zip manually fails and gives no reason as to why. Theme zip file is only 12.4Mb, so I don't think it's size related. 

<img width="986" alt="Screen Shot 2020-10-30 at 3 48 18 PM" src="https://user-images.githubusercontent.com/143515/97755513-56ae2700-1ac7-11eb-8bdf-957d9428aa3d.png">

**Comment by asiejnapsc** [comment]
> Having this same issue.
> 
> `stencil push` gives this:
> ![PixelSnap 2019-10-29 at 11 04 15@2x](https://user-images.githubusercontent.com/199599/67786117-54406980-fa3c-11e9-842f-6043b1b415d8.png)
> 
> Manually uploading gives this:
> ![PixelSnap 2019-10-29 at 09 53 11@2x](https://user-images.githubusercontent.com/199599/67787332-5b687700-fa3e-11e9-9508-04445b4ed1a8.png)
> 
> I don't doubt that there might be an issue with my theme, but the only error info available implies it's a BigCommerce server issue: `A server error occurred`

Was there ever a fix or response to this? We are getting the exact same undescriptive errors in both the Stencil CLI and manual upload in the admin of BigCommerce.

At a loss here trying to update our store to the newest release of Cornerstone (currently incrementally merging release commits - moving from 4.5.4 to 4.7.0).

**Comment by brandonjp** [comment]
@creativereason @asiejnapsc 
Any chance you're trying to push a Stencil theme to a store that's currently running an old Blueprint theme?

**Comment by asiejnapsc** [comment]
> @creativereason @asiejnapsc
> Any chance you're trying to push a Stencil theme to a store that's currently running an old Blueprint theme?

Hmm... well we already were on Stencil with Cornerstone 4.5.4 (current live theme running on store for the better part of a year). But I do know our store - at least some of the admin panel - is running legacy elements. Essentially, we _were_ on Blueprint before March of last year and made the switch around then and are finally getting around to fully updating to the newest Cornerstone theme.

Sorry not sure if that's related or what you meant. I'll take any insight you have though.

**Comment by brandonjp** [comment]
@asiejnapsc Just curious & hoping it would help. That wasn't our issue either, but BigC tried to blame it on that when we were dealing with it. 

Despite spending waaayyy toooo looooong troubleshooting this... There's not much advice I have that helps. My best advice would be to start now your theme on the latest Cornerstone version. I'd be happy to talk further about it (username @ gmail). But I'm not sure how much it will help.  Eventually, I just recreated our theme again on the latest Cornerstone and pushed it live to a test site nearly everyday to ensure it was working. We had no problems going live with the new version. It's just that we spent twice the amount of time for a site that is much simpler than planned. (But now we're in the process of upgrading/rebasing as well! So who knows what's in store!)

I am soooooo sorry you're having this problem. I don't mean to be overly dramatic here but... this issue literally ruined 6 months of my life and finances. My client would've fired me if he hadn't actually been on the phone with me when BigC finally admitted that they knew about the issue but wouldn't help. We spent hours on the phone with BigC (90% was spent re-explaining the issue to someone with no dev knowledge until they would finally transfer us). We finally worked directly with two of their engineers and sent them zip files of our theme. They checked them and confirmed that they run fine locally and even tried manually to apply it to our store... all to no avail. They essentially informed us that they don't have good enough logging on their end to troubleshoot the problem and the issue does not affect enough users for them to address it. Understandable, but infuriating and exhausting. This issue (along with a couple others!) has lead me to passionately steer all my clients since away from BigCommerce. After you get past this, things are mostly fine (mostly!) - we just simply lost confidence in BigC.

**Comment by keobrien** [comment]
In my case, `stencil push` reporting "A server error occurred" was an issue with the schema.json.

[Found the answer here](https://support.bigcommerce.com/s/question/0D51B00005PetbaSAB/receiving-a-server-error-occurred-when-i-used-stencil-push?language=en_US) for anyone curious. [The docs](https://developer.bigcommerce.com/stencil-docs/ZG9jOjE0MzE5MzM-theme-styles-configuration) do say that schema.json has a limit of 64 KB and there is no limit on the number of keys. In our case however, it looks like it’s allowing it up to 111 KB. Not sure if it’s the file size or the keys but removing 4 new keys I added in the update made it go through.
