### ISSUE TITLE
global `npm install` of stencil-cli fails on node 9.10.0 when on MacOS 10.13.3

### ISSUE THREAD

**Issue by qbunt** [bigcommerce/stencil-cli#374]
### Expected behavior
`npm install -g @bigcommerce/stencil-cli` installs without any npm error on Node v9.10.0

### Actual behavior
`npm install -g @bigcommerce/stencil-cli` when on Node 9.10.0 returns the following error message when building `lib-sass` via node-gyp

```
../src/sass_types/list.cpp:28:19: error: no matching function for call to
      'sass_make_list'
    return *out = sass_make_list(length, comma ? SASS_COMMA : SASS_SPACE);
                  ^~~~~~~~~~~~~~
/usr/local/include/sass/values.h:53:34: note: candidate function not viable:
      requires 3 arguments, but 2 were provided
ADDAPI union Sass_Value* ADDCALL sass_make_list    (size_t len, enum Sass...
                                 ^
1 error generated.
make: *** [Release/obj.target/binding/src/sass_types/list.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

### Steps to reproduce behavior
Switch to Node v9.10.0 and run `npm install -g @bigcommerce/stencil-cli`. Switching to the LTS release (8.11.1 as of this writing) installs without issue.

This does appear to be related to lib-sass/node-sass via node-gyp building when in this version. This may be outside the scope of what this project would like to handle, if so please close. Thanks!

**Comment by qbunt** [comment]
Also appears to affect 9.10.1, see below:

```
../src/sass_types/list.cpp:28:19: error: no matching function for call to
      'sass_make_list'
    return *out = sass_make_list(length, comma ? SASS_COMMA : SASS_SPACE);
                  ^~~~~~~~~~~~~~
/usr/local/include/sass/values.h:53:34: note: candidate function not viable:
      requires 3 arguments, but 2 were provided
ADDAPI union Sass_Value* ADDCALL sass_make_list    (size_t len, enum Sass...
                                 ^
1 error generated.
make: *** [Release/obj.target/binding/src/sass_types/list.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/REDACTED/.nvm/versions/node/v9.10.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Users/REDACTED/.nvm/versions/node/v9.10.1/bin/node" "/Users/REDACTED/.nvm/versions/node/v9.10.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/REDACTED/.nvm/versions/node/v9.10.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bigcommerce/node-sass@3.4.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @bigcommerce/node-sass@3.4.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by junedkazi** [comment]
@qbunt currently we do not support node 9.x https://stencil.bigcommerce.com/docs/prerequisites-mac-os#section--span-id-node-npm_mac-2-node-js-span-

We are looking into adding support for 9.x.

**Comment by qbunt** [comment]
Ah, I see that in the docs site, would you accept a PR to call that out in the Readme file here as well @junedkazi?
