### ISSUE TITLE
stencil start error with Cornerstone-2.0.0, Node version 4.6.1

### ISSUE THREAD

**Issue by ElynJin** [bigcommerce/stencil-cli#386]
I download the latest Cornerstone 2.0.0, there has errors when run stencil start, my Node version is 4.6.1.
pc system: win10 x64

error:
xxxx\stencil>stencil start
xxxx\stencil\node_modules\webpack\lib\Compiler.js:11
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (xxxx\stencil\node_modules\webpack\lib\webpack.js:7:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

The code in xxxx\stencil\node_modules\webpack\lib\Compiler.js:11 is here:
const {
	Tapable,
	SyncHook,
	SyncBailHook,
	AsyncParallelHook,
	AsyncSeriesHook
} = require("tapable");

**Comment by mattolson** [comment]
We are no longer supporting Node 4.x, which has reached EOL as of April 30, 2018. Please upgrade to 6.x or higher. 

https://github.com/nodejs/Release/blob/643af71ee8365efbdccaa134690425ea05931279/README.md#release-schedule
