### ISSUE TITLE
Bigcommerce responds with 500 error on stencil start command.

### ISSUE THREAD

**Issue by Bshally** [bigcommerce/stencil-cli#401]
### Expected behavior
Running stencil start -v ThemeName should run without issues.

### Actual behavior
#255 had the same issue. My situation is very similar to theirs. No code has been changed since last run. Only changes made have been in the BC dashboard:

1. Set HTTPS to run on all pages
2. Changed store from under maintenance to live

#### Troubleshooting attempted

I've toggled both of these to test. I've also added the s in https to the `.stencil` file and saved and tested. 

Additionally I've toggled off Cloudflare settings as recommended [in this bigcommerce forum post](https://forum.bigcommerce.com/s/question/0D51B00003sOAwfSAG/solved-the-bigcommerce-server-responded-with-a-500-error-using-stencil-cli-to-connect-to-store). It is worth noting that my two other stores have the same exact Cloudflare setup that this one did and have never experienced this issue.

None of the troubleshooting mentioned above has worked. 

#### Actual error code
Getting the following error code in the command line when attempting to load the local page:

```
Debug: internal, implementation, error 
    Error: Error: The BigCommerce server responded with a 500 error
    at /Users/myusername/.nvm/versions/node/v8.11.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:46:31
    at /Users/myusername/.nvm/versions/node/v8.11.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:135:20
    at finish (/Users/myusername/.nvm/versions/node/v8.11.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:249:20)
    at wrapped (/Users/myusername/.nvm/versions/node/v8.11.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:879:20)
    at ClientRequest.onResponse (/Users/myusername/.nvm/versions/node/v8.11.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:200:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
``` 

### Steps to reproduce behavior

Run stencil start from the commandline .

**Comment by karen-white** [comment]
Hey @Bshally , sorry for the late reply--are you still seeing this issue?

Could you try adding an entry to your local machine's hosts file using your BigCommerce IP address? You'll want to make sure you add entries for both the www and non-www versions of your domain. Let me know if this helps!

**Comment by ahmed-sigmalux** [comment]
I'm seeing the same issue. I'm also using Cloudflare.

**Comment by wearegoose** [comment]
I currently have the exact same issue. I have paused Cloudflare but still have the issue.

**Comment by wearegoose** [comment]
@ahmed-sigmalux Managed to get it working. I paused Cloudflare, still using their DNS setup, but not using firewalls, cache etc. 

We are also using CNAME flattening, so I am not sure if this caused issued. Anyway, I used the store's http permanent address in the .stencil configuration
