### ISSUE TITLE
while run the (stencil push -a light )command getting the below error

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#460]
SyntaxError: Unexpected token } in JSON at position 251
    at JSON.parse (<anonymous>)
    at fs.readFile (/opt/hostedtoolcache/node/8.16.0/x64/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-push.utils.js:47:26)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
##[error]Bash exited with code '1'.

could you please help me on this................

**Comment by jeremysimmons** [comment]
Duplicate of #459 - probably need to close

**Comment by karen-white** [comment]
@mahammad13 Were you able to resolve this on #459 ? If so, please feel free to close this one out or let us know if you still need help. Thanks!
