### ISSUE TITLE
while push theme to bigcommerce using stencil push -a Light getting below error?

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#464]
2019-05-16T17:45:03.4550861Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/9c5b021d-aeb1-41bf-b783-7dfbc318db0f.sh
2019-05-16T17:45:05.6060416Z Validating theme...
2019-05-16T17:45:05.6804329Z Running ESLint...
2019-05-16T17:45:05.6940466Z 
2019-05-16T17:45:05.6978747Z SCSS Parsing Started...
2019-05-16T17:45:05.6979090Z Template Parsing Started...
2019-05-16T17:45:05.6979413Z Language Files Parsing Started...
2019-05-16T17:45:05.6979925Z Building Theme Schema File...
2019-05-16T17:45:05.7564204Z Theme task Started...
2019-05-16T17:45:05.7664993Z /opt/hostedtoolcache/node/8.16.0/x64/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:113
2019-05-16T17:45:05.7665422Z             const filterFiles = files.filter((file) => {
2019-05-16T17:45:05.7665683Z                                       ^
2019-05-16T17:45:05.7665801Z 
2019-05-16T17:45:05.7666699Z TypeError: Cannot read property 'filter' of undefined
2019-05-16T17:45:05.7667154Z     at Fs.readdir (/opt/hostedtoolcache/node/8.16.0/x64/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:113:39)
2019-05-16T17:45:05.7667356Z     at FSReqWrap.oncomplete (fs.js:135:15)
2019-05-16T17:45:05.7752587Z ##[debug]Exit code 1 received from tool '/bin/bash'
2019-05-16T17:45:06.2930542Z ##[debug]STDIO streams have closed for tool '/bin/bash'
2019-05-16T17:45:06.3011624Z ##[error]Bash exited with code '1'.
2019-05-16T17:45:06.3023059Z ##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '1'.
2019-05-16T17:45:06.3023336Z ##[debug]task result: Failed
2019-05-16T17:45:06.3024376Z ##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
2019-05-16T17:45:06.3026446Z ##[section]Finishing: Command Line Script
![stencil cli](https://user-images.githubusercontent.com/41624407/57876080-17880980-7832-11e9-989f-2420a53bf4c2.png)

**Comment by mahammad13** [comment]
please help me on this

**Comment by karen-white** [comment]
@mahammad13 That looks like a JS error in the theme. Have you tracked this down in your theme files?
`const filterFiles = files.filter((file) => {`

it looks like the `file` data being passed in might not be valid.

**Comment by mahammad13** [comment]
sorry karen.. i don't know where to track and also i can not see any theme file here..
 please help me on this issue..
Thanks
Mahammad

**Comment by karen-white** [comment]
Hey @mahammad13 , I'm a little confused. When you say you can't see any theme files, where are the files for the theme you're bundling and pushing to the store? Do you mean that if you do a search through the theme files, that line of code doesn't exist?

**Comment by mahammad13** [comment]
![image](https://user-images.githubusercontent.com/41624407/58008149-67542280-7b09-11e9-8a40-b4c2957aba20.png)
We have seen in the above screen related to themes. are you referring to the above mentioned theme?
Please suggest how to fix this issue

**Comment by karen-white** [comment]
Hey @mahammad13 , on second look I don't think the error is coming from the theme files themselves--it's throwing the error [here](https://github.com/bigcommerce/stencil-cli/blob/24010328d555432c5d20b54ddf6b4c01c7630211/lib/stencil-bundle.js#L113) when the theme bundle job starts. That's really odd. It suggests that no files are being passed into fs.readdir(). Is there any other info you can provide about the way your pipeline is set up? Is the pipeline yaml file in the root directory of your theme? It almost suggests that the command is being run out of directory, or something similar.

**Comment by mahammad13** [comment]
Hi Karen thanks for your inputs..
Here i have created azure build pipeline for the theme push to big commerce ..(generate artifacts , artifacts inlcude all file like .stencil ,zip file) and then use release pipeline (here we use (stencil push -a light )cmd ..
see the below build pipeline..
![image](https://user-images.githubusercontent.com/41624407/58235560-ae872100-7d5e-11e9-8965-0446d44e5527.png)
 see the below release pipeline ..
![image](https://user-images.githubusercontent.com/41624407/58235619-d1193a00-7d5e-11e9-8c8f-697da1a22165.png)

please help on this and let me know if you need any information
