### ISSUE TITLE
Stencil CLI Install Fails at Node-Sass

### ISSUE THREAD

**Issue by VH-WRK** [bigcommerce/stencil-cli#502]
### Actual behavior
In stall of Stencil fails on node-sass. Getting the below error:

```
782 silly resolveWithNewModule postcss@5.2.18 checking installable status
783 silly pacote Retrying git command: ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git attempt # 2
784 silly pacote Retrying git command: ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git attempt # 3
785 silly fetchPackageMetaData error for @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.4.4 Error while executing:
785 silly fetchPackageMetaData /usr/local/git/bin/git ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
785 silly fetchPackageMetaData
785 silly fetchPackageMetaData fatal: unable to connect to github.com:
785 silly fetchPackageMetaData github.com[0: 52.64.108.95]: errno=Operation timed out
785 silly fetchPackageMetaData
785 silly fetchPackageMetaData
785 silly fetchPackageMetaData exited with error code: 128
786 timing stage:rollbackFailedOptional Completed in 1ms
787 timing stage:runTopLevelLifecycles Completed in 240319ms
788 verbose stack Error: exited with error code: 128
788 verbose stack     at ChildProcess.<anonymous> (/Users/vhaddad/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
788 verbose stack     at emitTwo (events.js:125:13)
788 verbose stack     at ChildProcess.emit (events.js:213:7)
788 verbose stack     at maybeClose (internal/child_process.js:887:16)
788 verbose stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
788 verbose stack     at emitOne (events.js:115:13)
788 verbose stack     at Socket.emit (events.js:210:7)
788 verbose stack     at Pipe._handle.close [as _onclose] (net.js:548:12)
789 verbose cwd /Users/vhaddad/BigCommerce/ReadingEggsShop/cornerstone
790 verbose Darwin 16.7.0
791 verbose argv "/Users/vhaddad/.nvm/versions/node/v8.1.0/bin/node" "/Users/vhaddad/.nvm/versions/node/v8.1.0/bin/npm" "install" "-g" "@bigcommerce/stencil-cli"
792 verbose node v8.1.0
793 verbose npm  v6.10.2
794 error Error while executing:
794 error /usr/local/git/bin/git ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
794 error
794 error fatal: unable to connect to github.com:
794 error github.com[0: 52.64.108.95]: errno=Operation timed out
794 error
794 error
794 error exited with error code: 128
795 verbose exit [ 1, true ]
```

### Steps to reproduce behavior
Running macOS Sierra 10.12.6
node v8.1.0
npm v6.10.2

**Comment by karen-white** [comment]
Hey @VH-WRK , are you behind a firewall that could be blocking the connection to GitHub? Might be worth trying the solution outlined here:

https://stackoverflow.com/a/18889129/8521556
https://github.com/angular/angular-phonecat/issues/141

**Comment by VH-WRK** [comment]
> Hey @VH-WRK , are you behind a firewall that could be blocking the connection to GitHub? Might be worth trying the solution outlined here:
> 
> https://stackoverflow.com/a/18889129/8521556
> [angular/angular-phonecat#141](https://github.com/angular/angular-phonecat/issues/141)

Thanks @karen-white that worked!

**Comment by Bader322** [comment]
Worked for me too. Thank you
