### ISSUE TITLE
SCSS saves do not update without page refresh

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/stencil-cli#511]
### Expected behavior
When developing locally, scss file saves would inject new changes (no page reload). 

### Actual behavior
My terminal is showing that browsersync is reading the changes, but no updates are happening
<img width="983" alt="browserstc" src="https://user-images.githubusercontent.com/5169882/63533399-559c6580-c4d2-11e9-9508-ca13dc4f388d.png">

### Steps to reproduce behavior
Node 8.11.3
MacOs Mohave 10.14.6

My team noticed this happening when we started using cornerstone v 4, but it seems to me more related to the CLI. We have also noticed a lot of other issues as far as 500 internal server errors when using product filtering and adding to cart, but I will open a new issue for that

**Comment by anvucodespot** [comment]
We have the same issue, the CSS hot reload doesn't work.
Node: v8.16.0
OS: Debian 9.9

**Comment by sacr3dc0w** [comment]
Entire team here has experienced all of the issues you've stated.

- Dramatic increase in 500 internal server errors
- Issues adding products to cart
- SCSS does not automatically refresh as before.

**Comment by code-man** [comment]
@karen-white is there somewhere I can follow these tickets? I'm patiently waiting as I'm stalled on adding a theme feature that's holding up 2 of our stores

**Comment by karen-white** [comment]
Hey @code-man , we're tracking these tickets through our support system, so our tech support team will have visibility into the status (and I've made a note to update this GitHub issue when we close those tickets out). But, I believe we've found a workaround that might alleviate some of these issues in the short term. Can you try upgrading to Node 8.16.x and see if that resolves some of these issues on your end?

**Comment by code-man** [comment]
Hey @karen-white thanks for your reply again; much appreciated.

Same errors running 8.16

<img width="722" alt="image" src="https://user-images.githubusercontent.com/3812251/63954799-afaca600-ca51-11e9-9810-025c35f2de96.png">

![image](https://user-images.githubusercontent.com/3812251/63954779-a6233e00-ca51-11e9-892f-12b2e78e28b0.png)

**Comment by karen-white** [comment]
Thanks for testing @code-man - this is a good data point for our investigation. We'll keep you posted

**Comment by code-man** [comment]
@karen-white copied the logged output from the Stencil CLI. Perhaps this will be of some additional help:

Debug: internal, implementation, error 
    Error: Error: The BigCommerce server responded with a 500 error
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:45:31
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:134:20
    at finish (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:249:20)
    at wrapped (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:879:20)
    at ClientRequest.onResponse (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:200:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
Debug: internal, implementation, error 
    Error: Error: The BigCommerce server responded with a 500 error
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:45:31
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:134:20
    at finish (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:249:20)
    at wrapped (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:879:20)
    at ClientRequest.onResponse (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:200:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
Debug: internal, implementation, error 
    Error: Error: The BigCommerce server responded with a 500 error
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:45:31
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:134:20
    at finish (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:249:20)
    at wrapped (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:879:20)
    at ClientRequest.onResponse (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:200:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
Debug: internal, implementation, error 
    Error: Error: The BigCommerce server responded with a 500 error
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:45:31
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:134:20
    at finish (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:249:20)
    at wrapped (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:879:20)
    at ClientRequest.onResponse (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:200:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
Debug: internal, implementation, error 
    Error: Error: The BigCommerce server responded with a 500 error
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:45:31
    at /Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:134:20
    at finish (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:249:20)
    at wrapped (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:879:20)
    at ClientRequest.onResponse (/Users/cody/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:200:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)

**Comment by kylebolstad** [comment]
It seems to be a change introduced in @bigcommerce/stencil-cli@1.18.0. I am currently running v1.17.0 until this bug is fixed.

**Comment by code-man** [comment]
Is there a way to rollback the Stencil CLI version to a previous version? I've tried uninstalling and installing using a version # but providing a version # like '@1.16.0' didn't work for me.

**Comment by kylebolstad** [comment]
@code-man 

Installation instructions at https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil are detailed and correct. 

Since I use node v8.16.0 with nvm on a Mac, I did this to rollback Stencil CLI v1.20.0 to v1.17.0:

`nvm use 8.16;`
`npm uninstall -g @bigcommerce/stencil-cli;`
`npm i -g @bigcommerce/stencil-cli@1.17.0;`

**Comment by code-man** [comment]
@kylebolstad 

Successfully rolled back this time. Awesome, thanks for that. Running 1.17 now and everything is working again as expected.

As mentioned, it seems to have been introduced back at 1.18.0 as you found as well
