### ISSUE TITLE
NPM Install ERROR when run the pipeplines on bitubucket

### ISSUE THREAD

**Issue by tantv** [bigcommerce/stencil-cli#527]
### Expected behavior
I tried to run the pipelines on bitbucket but this turns out to be a long error message (see below).
This work well two weeks ago but at the moment it failed

I checked issue #417 but it not work.

Besides that, the docs (https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil) has updated with the different requirements for the node version.
I also update as the docs but the issue still happen

### Actual behavior
```
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/.node-gyp/7.9.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/.node-gyp/7.9.0/include/node -I/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/.node-gyp/7.9.0/src -I/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/.node-gyp/7.9.0/deps/openssl/config -I/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/.node-gyp/7.9.0/deps/openssl/openssl/include -I/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/.node-gyp/7.9.0/deps/uv/include -I/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/.node-gyp/7.9.0/deps/zlib -I/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/.node-gyp/7.9.0/deps/v8/include -I../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:0:
../src/sass_context_wrapper.h:8:26: fatal error: sass/context.h: No such file or directory
 #include <sass/context.h>
                          ^
compilation terminated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
binding.target.mk:116: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: Leaving directory '/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.50-coreos-r1
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@bigcommerce/stencil-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bigcommerce/node-sass@3.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bigcommerce/node-sass@3.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Steps to reproduce behavior
```
image: node:7.9.0
pipelines:
  custom:
    develop:
      - step:
          caches:
           - node
          script:
           - npm install
            - npm install -g @bigcommerce/stencil-cli@1.15.9
            - stencil push -a Light
```

**Comment by junedkazi** [comment]
can you try with the latest 3.x version. Please re-open or file a new issue if you are still experiencing issue.
