### ISSUE TITLE
The `libsass` binding was not found on running "stencil start"

### ISSUE THREAD

**Issue by shreyaspadhye3011** [bigcommerce/stencil-cli#594]
### Expected behavior
Expected to launch the theme locally

### Actual behavior
The `stencil start` command results in "The `libsass` binding was not found". I followed the steps given here: https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/live-previewing-a-theme 

 I also tried `npm rebuild node-sass` but it does not fix the issue

**Log:**
```
(node:23944) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/vendor/darwin-x64-64/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/lib/index.js:16:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/lib/styles.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by mattpantoja** [comment]
I ran into this exact same issue, and `npm rebuild node-sass` as well as `npm rebuild @bigcommerce/node-sass` were unsuccessful in getting me up and running. Here was my error message:
```
/Users/[username]/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /Users/[username]/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/vendor/darwin-x64-64/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/Users/[username]/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/Users/[username]/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/lib/index.js:16:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/[username]/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/lib/styles.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/[username]/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/lib/index.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```
(replaced my username with `[username]`). This was after a clean install of both npm/node/nvm and stencil following the directions [here](https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil) exactly with versions matching across the board.

I ended up investigating my local globally installed instance of @bigcommerce/stencil-cli by navigating to that directory:
```
cd /Users/[username].nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass
```
and noticed there was no vendor folder present which was throwing this error. 

I ended up manually building out BC's version of `node-sass` using this [repo](https://github.com/bigcommerce-labs/node-sass) which did have a vendor folder in it once setup. I navigated back to my local copy of `@bigcommerce/stencil-cli` and copied the vendor folder to the nested  `node_modules/@bigcommerce/node-sass` directory and then stencil worked without incident.

**Comment by junedkazi** [comment]
Can you try the latest 3.x version to see if it resolves this issue.

**Comment by danielebra** [comment]
@junedkazi I encountered this same issue.

Rebuilding bigcommerce node-sass and transfering the `vendor` file to nvm node modules directory resolved this issue (as defined by @mattpantoja)

Extract from [bigcommerce node-sass readme](https://github.com/bigcommerce-labs/node-sass#rebuilding-binaries):

```sh
git clone --recursive https://github.com/sass/node-sass.git
cd node-sass
git submodule update --init --recursive
npm install
node scripts/build -f 

```

transfer the vendor folder:

```sh
cp -r vendor $YOUR_NODE_SASS_DIR
```
