### ISSUE TITLE
Stencil Bundle / Pull throws error 

### ISSUE THREAD

**Issue by hicondron** [bigcommerce/stencil-cli#598]
### Expected behavior
stencil bundle

### Actual behavior
Error: Your theme's schema.json has errors:
schema[11].settings[0].options[0].value should be string,number
schema[11].settings[0].options[1].value should be string,number
    at validateJsonSchema (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\lib\bundle-validator.js:134:16)
    at BundleValidator.validateThemeSchema (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\lib\bundle-validator.js:78:23)
    at C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:3880:24
    at replenish (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:1011:17)
    at C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:1016:9
    at eachOfLimit (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:1041:24)
    at C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:1046:16
    at _parallel (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:3879:5)
    at Object.series (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:4735:5)
    at BundleValidator.validateTheme (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\lib\bundle-validator.js:55:11)
    at Bundle.validateTheme (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\lib\stencil-bundle.js:288:20)
    at C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:3880:24
    at replenish (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:1011:17)
    at C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:1016:9
    at eachOfLimit (C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:1041:24)
    at C:\ProgramData\nvm\v10.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:1046:16

### Steps to reproduce behavior
only happens on certain theme files.  My coworker does not have the same issue.  We are running the same node and stencil cli versions, etc. I uninstalled/reinstalled chocolatey, git, python, nvm and node and the error repeated. I did a diff check of the schema.json file between my coworker and I and there is no difference.

**Comment by flair-chris** [comment]
@hicondron 
If this is a cli error, then some more information would be helpful such as OS, node version npm version etc.
Also your schema.json contents would also be helpful.

**Comment by thanicricket** [comment]
@flair-chris this cli error only replicate otherthan cornerstone theme files. So please try with otherthan cornerstone theme. Please fix as soon as possible.

**Comment by thanicricket** [comment]
> @flair-chris this cli error only replicate otherthan cornerstone theme files. So please try with otherthan cornerstone theme. Please fix as soon as possible.



> @hicondron
> If this is a cli error, then some more information would be helpful such as OS, node version npm version etc.
> Also your schema.json contents would also be helpful.

@flair-chris 
this cli error only replicate otherthan cornerstone theme files. So please try with otherthan cornerstone theme. Please fix as soon as possible.
