### ISSUE TITLE
500 error on single store

### ISSUE THREAD

**Issue by Bobspadger** [bigcommerce/stencil-cli#660]
### Expected behavior
Working local development site

### Actual behavior
500 server error

### Steps to reproduce behavior
using stencil cli 2.1.1 (as this is the required version for our theme) I have tested on 3.x.x and have similar errors.

Using our theme : supermarket 4.7.0

- Using our dev store - all fine
- Using our live production store - 500 errors on attempting to access localhost:3000
- Using another of our stores - all fine

Creating a new directory, and cloning cornerstone theme into it
- Using our dev store - all fine
- Using our live production store - 500 errors on attempting to access localhost:3000
- Using another of our stores - all fine

Output from stencil-cli after attempting to access localhost:3000

```bash
Node Version: v10.16.3

-------------------------------------------------

[Browsersync] Proxying: http://localhost:3001
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.185:3000
 --------------------------------------
          UI: http://localhost:3002
 UI External: http://localhost:3002
 --------------------------------------
[Browsersync] Watching files...
Validating schema.json...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Webpack Bundle Analyzer saved report to /Users/Shared/GIT/bigcommerce/assets/dist/report.html
[Browsersync] Reloading Browsers...
Debug: internal, implementation, error
    Error: Error: The BigCommerce server responded with a 500 error
    at /Users/ash/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:45:31
    at /Users/ash/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:134:20
    at finish (/Users/ash/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:249:20)
    at wrapped (/Users/ash/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:879:20)
    at ClientRequest.onResponse (/Users/ash/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:200:20)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:466:23)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:466:23)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
```

output from browser:

```json
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "An internal server error occurred"
}
```

It seems it may be something to do with our live production store - however, BC support do not seem to see if this way.

**Comment by junedkazi** [comment]
@Bobspadger do you use some kind of DNS proxy on the store where you are experiencing this issue ? If you don't mind can you share your store details with me at  my firstname.lastname@bigcommerce.com

**Comment by Bobspadger** [comment]
@junedkazi we do have Cloudflare on - could this be it?

**Comment by junedkazi** [comment]
Thanks @Bobspadger I will get a PR in place to document this info. I am going to close this ticket.
