### ISSUE TITLE
Error: \\mixins\\grid.scss doesn't exist

### ISSUE THREAD

**Issue by rickeydute** [bigcommerce/stencil-cli#688]
### Expected behavior
When Stencil starts and links with the browser, it should load all files in the folder.
### Actual behavior
The page loads in the browser but the CSS does not load giving out the following error: 
```
Error: \mixins\grid.scss doesn't exist!
    at options.error (E:\Git\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@bigcommerce\node-sass\lib\index.js:277:32) {
  formatted: "Error: \\mixins\\grid.scss doesn't exist!\n        on line 7 " +
    'of custom.scss\n>> @import "/mixins/grid";\n   --------^\n',
  message: "\\mixins\\grid.scss doesn't exist!",
  column: 9,
  line: 7,
  file: 'custom.scss',
  status: 1
}
```
### Steps to reproduce behavior
Type stencil start in the terminal and let the page load. 

------

**Comment by obrien-k** [comment]
> ### Expected behavior
> When Stencil starts and links with the browser, it should load all files in the folder.
> 
> ### Actual behavior
> The page loads in the browser but the CSS does not load giving out the following error:
> 
> ```
> Error: \mixins\grid.scss doesn't exist!
>     at options.error (E:\Git\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@bigcommerce\node-sass\lib\index.js:277:32) {
>   formatted: "Error: \\mixins\\grid.scss doesn't exist!\n        on line 7 " +
>     'of custom.scss\n>> @import "/mixins/grid";\n   --------^\n',
>   message: "\\mixins\\grid.scss doesn't exist!",
>   column: 9,
>   line: 7,
>   file: 'custom.scss',
>   status: 1
> }
> ```
> 
> ### Steps to reproduce behavior
> Type stencil start in the terminal and let the page load.

Hey there,

Could you share the contents of `custom.scss` ?

Best,
Kyle O.
