### ISSUE TITLE
"cannot find module webpack"

### ISSUE THREAD

**Issue by steppinonland** [bigcommerce/stencil-cli#707]
@leeBigCommerce @jimmybigcommerce please help!!

### Expected behavior
my changes can get pushed to Big Commerce from my powershell

### Actual behavior
i get this error about webpack
```
PS C:\Users\slandgraf\Documents\Webstores\stickershop-virginiaNAACP> stencil push
Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Schema Translations Parsing Started...
Theme task Started...
ok -- Schema Translations Parsing Finished
ok -- Language Files Parsing Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Template Parsing Finished
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module './webpack.prod.js'
Require stack:
- C:\Users\slandgraf\Documents\Webstores\stickershop-virginiaNAACP\stencil.conf.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at production (C:\Users\slandgraf\Documents\Webstores\stickershop-virginiaNAACP\stencil.conf.js:43:22)
    at process.<anonymous> (C:\Users\slandgraf\Documents\Webstores\stickershop-virginiaNAACP\stencil.conf.js:64:13)
    at process.emit (events.js:314:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\slandgraf\\Documents\\Webstores\\stickershop-virginiaNAACP\\stencil.conf.js'
  ]
}
failed  -- worker terminated


not ok -- Error: worker terminated

Please visit the troubleshooting page https://developer.bigcommerce.com/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.
If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.
PS C:\Users\slandgraf\Documents\Webstores\stickershop-virginiaNAACP>
```

### Steps to reproduce behavior
not sure what this means ?

**Comment by junedkazi** [comment]
@steppinonland how old is your theme fork. If you have forked off of cornerstone you should have something like this https://github.com/bigcommerce/cornerstone/blob/master/webpack.prod.js

**Comment by steppinonland** [comment]
great question. I don't know how old my theme is. let me ask someone on my team!

**Comment by steppinonland** [comment]
it's a couple years old
