### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by jacobnoah** [bigcommerce/stencil-cli#721]
### Expected behavior
I expected to be able to install stencil-cli no problem.

### Actual behavior
Using correct versions of npm and node I keep getting this error in npm:
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path ../node/v10.24.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/lodash
npm ERR! dest ../.nvm/versions/node/v10.24.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/.lodash.DELETE
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '../.nvm/versions/node/v10.24.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/lodash' -> '../.nvm/versions/node/v10.24.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/.lodash.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

I have done everything from uninstalling npm and node as well as removing package-lock.json and node_modules folder. I have tried installing it locally and globally and get the same error. I have tried all solutions online including quitting all instances of nodes running. I have even restarted my computer and have 0 applications running and I still get the same error. I am unsure of why this keeps happening on my system. I should specify I have a Mac. 

### Steps to reproduce behavior
doing npm i -g @bigcommerce/stencil-cli or npm i @bigcommerce/stencil-cli

**Comment by jairo-bc** [comment]
Hi @jacobnoah,

Could you please provide node version by typing `node -v`?

**Comment by gotts2swim** [comment]
@jacobnoah I encountered a similar issue when using npm version 7. In my case, npm was unable to resolve the 'mkdir' module. If I downgrade to npm version 6, it installs no problem.

Perhaps you could try downgrading to version 6 and see if that resolves your issue.

@jairo-bc any idea what may be causing this issue? My gut feeling is it has to do with on or more outdated dependencies but I'm not entirely sure that's what it is.

Here's the output from running `npm install -g @bigcommerce/stencil-cli` with npm v7.23.0 on node v12.22.6:
```
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/teamwork@3.3.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/vise@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/subtext@6.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/statehood@6.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/podium@3.4.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/mimos@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/nigel@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/heavy@6.2.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/content@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/file@1.0.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/cryptiles@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox-memory@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/ammo@3.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @hapi/pez@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/iron@5.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/b64@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@8.0.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated @hapi/somever@2.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/shot@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/call@5.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/accept@3.2.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/bounce@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox@10.2.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/wreck@15.1.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated @hapi/hoek@6.2.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hapi@18.4.1: This version contains severe security issues and defects and should not be used! Please upgrade to the latest version of @hapi/hapi or consider a commercial license (https://github.com/hapijs/hapi/issues/4114)
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/cory/.nvm/versions/node/v12.22.6/bin/node /Users/cory/.nvm/versions/node/v12.22.6/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/cory/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/cory/.npm/_cacache/tmp/git-cloneXiO7cf
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node scripts/install.js
npm ERR! npm ERR! internal/modules/cjs/loader.js:818
npm ERR! npm ERR!   throw err;
npm ERR! npm ERR!   ^
npm ERR! npm ERR! 
npm ERR! npm ERR! Error: Cannot find module 'mkdirp'
npm ERR! npm ERR! Require stack:
npm ERR! npm ERR! - /Users/cory/.npm/_cacache/tmp/git-cloneXiO7cf/scripts/install.js
npm ERR! npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR! npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
npm ERR! npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR! npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! npm ERR!     at Object.<anonymous> (/Users/cory/.npm/_cacache/tmp/git-cloneXiO7cf/scripts/install.js:7:13)
npm ERR! npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR! npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR! npm ERR!   requireStack: [
npm ERR! npm ERR!     '/Users/cory/.npm/_cacache/tmp/git-cloneXiO7cf/scripts/install.js'
npm ERR! npm ERR!   ]
npm ERR! npm ERR! }
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/cory/.npm/_logs/2021-09-15T22_34_28_195Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cory/.npm/_logs/2021-09-15T22_34_30_530Z-debug.log
```

**Comment by ImTheDeveloper** [comment]
Fixed by downgrading npm back to v6 - errors on v7 as above post showed.

**Comment by Nihir10dec** [comment]
Check NPM version using `npm -v`
If it's not version 6 downgrade or upgrade it by doing `npm i -g npm@6`

**Comment by steve-ross** [comment]
@jairo-bc not a fix, but at least there might be some advanced warning that you need npm@6 would be to add an engines declaration to package.json

```
"engines" : { 
    "node": "^10.17 || ^12",
    "npm": ">=v6.14.6 <7.0.0"
  }
``

**Comment by jairo-bc** [comment]
@steve-ross Thanks for suggestion! 
https://github.com/bigcommerce/stencil-cli/pull/846
