### ISSUE TITLE
Stencil Start fails, possible access token issue?

### ISSUE THREAD

**Issue by aisflat439** [bigcommerce/stencil-cli#753]
### Expected behavior

`stencil start` should work.

### Actual behavior
Error case renders

```bash
    Error: Could not fetch the rendered regions for this page type: Request failed with status code 400
    at Object.getRenderedRegionsByPageType (/Users/devinfitzsimons/.nvm/versions/node/v12.22.6/lib/node_modules/@bigcommerce/stencil-cli/lib/content-api-client.js:45:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Steps to reproduce behavior

System info:
```
m1 macbook
nvm
node -v 
  // v12.22.6
stencil --version 
  // 3.4.2
```

Stencil `---Startup Information---`output:
```base
config.stencil.json location: /Users/devinfitzsimons/Backup/BigCommerce/cornerstone/config.stencil.json
secrets.stencil.json location: /Users/devinfitzsimons/Backup/BigCommerce/cornerstone/secrets.stencil.json
config.json location: /Users/devinfitzsimons/Backup/BigCommerce/cornerstone/config.json
Store URL: http://[MY_STORE].mybigcommerce.com
SSL Store URL: https://[MY_STORE_URL].mybigcommerce.com
Node Version: v12.22.6
```

### What have I found so far

The error appears to be in content-api-client.js. The surprising result is that no matter what I change the access token to in my `secrets.stencil.json` i get the same `accessToken` value in the `getRenderedRegionsByPageType` funtion for `accessToken`. The values for `storeUrl` and `pageType` seem to be correct, `[mystoreurl.in.startup.information]` and `HOME` respectively. 

I've swapped out a few different API keys in case that's the issue. It doesn't appear to be.

I did find [this similar issue](https://support.bigcommerce.com/s/question/0D54O00006o2hLcSAI/issue-connecting-to-existing-store-with-cornerstone-theme-using-stencil-cli?language=en_US) in support. This makes me think that the `accessToken` is likely to be the issue. In my case, since I'm always getting the same value for `accessToken` no matter what I set it to, that's my best guess. Happy to add any info I can.

**Comment by aisflat439** [comment]
I took a bit of time off this project, tried out the cli again, and this time it worked.

I was promted to re-install the CLI to a more recent version. That seems to have solved this issue. I'll close
