### ISSUE TITLE
Error: ScssCompiler is used without activating specific implementation（after stencil start）

### ISSUE THREAD

**Issue by JinMengmeng1998** [bigcommerce/stencil-cli#835]
Error: ScssCompiler is used without activating specific implementation
    at ScssCompiler._assertEngineIsActive (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@bigcommerce\stencil-styles\lib\ScssCompiler.js:44:19)
    at ScssCompiler.compile (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@bigcommerce\stencil-styles\lib\ScssCompiler.js:69:14)
    at StencilStyles.compileCss (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@bigcommerce\stencil-styles\lib\styles.js:29:40)
    at internals.cssHandler (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\server\plugins\theme-assets\theme-assets.module.js:90:41)
    at async module.exports.internals.Manager.execute (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@hapi\hapi\lib\toolkit.js:45:28)
    at async Object.internals.handler (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@hapi\hapi\lib\handler.js:46:20)
    at async exports.execute (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@hapi\hapi\lib\handler.js:31:20)
    at async Request._lifecycle (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@hapi\hapi\lib\request.js:312:32)
    at async Request._execute (C:\ProgramData\nvm\v12.0.0\node_modules\@bigcommerce\stencil-cli\node_modules\@hapi\hapi\lib\request.js:221:9)

**Comment by marian-ene-customsoft** [comment]
Same here, it looks like it doesn't find a sass engine...

**Comment by JinMengmeng1998** [comment]
> 

Thanks so much .Using your method my theme does appear locally .But not in the same way as the online url....Do you have any questions like that?

**Comment by JinMengmeng1998** [comment]
> 同样在这里，它似乎没有找到一个sass引擎......
> 
> 找到了一个临时修复，但仍然不知道为什么会出现问题：
> 
> * 在  _...\nvm\v12.22.9\node_modules@bigcommerce\stencil-cli\node_modules@bigcommerce\stencil-styles\lib\ScssCompiler.js_添加**this.engine = require('@bigcommerce/node-sass'); **到 _ _assertEngineIsActive() {...}_方法的顶部。它似乎为我解决了这个问题。

Thanks so much .Using your method my theme does appear locally .But not in the same way as the online url....Do you have any questions like that?

**Comment by JinMengmeng1998** [comment]
> 

Thanks so much .Using your method my theme does appear locally .But not in the same way as the online url....Do you have any questions like that?

**Comment by JinMengmeng1998** [comment]
> 同样在这里，它似乎没有找到一个sass引擎......
> 
> 找到了一个临时修复，但仍然不知道为什么会出现问题：
> 
> * 在  _...\nvm\v12.22.9\node_modules@bigcommerce\stencil-cli\node_modules@bigcommerce\stencil-styles\lib\ScssCompiler.js_添加**this.engine = require('@bigcommerce/node-sass'); **到 _ _assertEngineIsActive() {...}_方法的顶部。它似乎为我解决了这个问题。

Thanks so much .Using your method my theme does appear locally .But not in the same way as the online url....Do you have any questions like that?

**Comment by marian-ene-customsoft** [comment]
No, sorry. Mine looks the same.

**Comment by marian-ene-customsoft** [comment]
You should try a reinstall tho, the latest update looks like it should have fixed the issue:
`3.8.3 (2022-01-12)
fix: add activate sass engine name logic (837)`

**Comment by sacr3dc0w** [comment]
> You should try a reinstall tho, the latest update looks like it should have fixed the issue: `3.8.3 (2022-01-12) fix: add activate sass engine name logic (837)`

I can confirm that running `npm install -g @bigcommerce/stencil-cli` resolves the issue.
