### ISSUE TITLE
Error: Module Build Failed

### ISSUE THREAD

**Issue by liamxtensive** [bigcommerce/stencil-cli#934]
### Expected behavior

Trying to run an older Cornerstone site locally.

### Actual behavior

Not loading correctly, product feeds are not loading and are just showing loading icons.

Getting the following error in console:

Error: Module build failed: TypeError: /xxx/assets/js/theme/global/quick-search.js: Cannot read property 'has' of undefined
    at resolvePath (/xxx/node_modules/babel-plugin-lodash/lib/importModule.js:22:24)
    at importModule (/xxx/node_modules/babel-plugin-lodash/lib/importModule.js:36:53)
    at memoized (/xxx/node_modules/lodash/memoize.js:62:23)
    at /xxx/node_modules/babel-plugin-lodash/lib/index.js:217:63
    at arrayEach (/xxx/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/xxx/node_modules/lodash/forEach.js:38:10)
    at /xxx/node_modules/babel-plugin-lodash/lib/index.js:193:30
    at arrayEach (/xxx/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/xxx/node_modules/lodash/forEach.js:38:10)
    at /xxx/node_modules/babel-plugin-lodash/lib/index.js:181:28

### Environment

Mac OS Monterey V12.0.1

Stencil-cli version `stencil --version`: 4.1.0

Node version `node -v`: 14.9.3

NPM version `npm -v`: 8.10.0

OS: Monterey V12.0.1

**Comment by jairo-bc** [comment]
Hi @liamxtensive, which cornerstone are you using?

**Comment by liamxtensive** [comment]
V1.11.0 so an oldie.
