### ISSUE TITLE
Can't install on Monterey 12.5.1

### ISSUE THREAD

**Issue by iovoz** [bigcommerce/stencil-cli#976]
npm install -g @bigcommerce/stencil-cli

### Expected behavior
install success

### Actual behavior
install failure

### Steps to reproduce behavior
 npm install -g @bigcommerce/stencil-cli

### Environment
See below.

Stencil-cli version `stencil --version`:
latest version

Node version `node -v`:
node v14.17.3

NPM version `npm -v`:
npm  v8.19.1

OS: MacOS Monterery 12.5.1

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/18189938/188208886-3f0120ef-a77d-4c15-a78c-b8f47fa54187.png">

2917 verbose Darwin 21.6.0
2918 verbose node v14.17.3
2919 verbose npm  v8.19.1
2920 error code 1
2921 error git dep preparation failed
2922 error command /Users/riovo/.nvm/versions/node/v14.17.3/bin/node /Users/riovo/.nvm/versions/node/v14.17.3/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/riovo/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
2923 error npm WARN using --force Recommended protections disabled.
2923 error npm ERR! code 1
2923 error npm ERR! path /Users/riovo/.npm/_cacache/tmp/git-cloneMLx5LV
2923 error npm ERR! command failed
2923 error npm ERR! command sh -c -- node scripts/install.js
2923 error npm ERR! internal/modules/cjs/loader.js:905
2923 error npm ERR!   throw err;
2923 error npm ERR!   ^
2923 error npm ERR! 
2923 error npm ERR! Error: Cannot find module 'mkdirp'
2923 error npm ERR! Require stack:
2923 error npm ERR! - /Users/riovo/.npm/_cacache/tmp/git-cloneMLx5LV/scripts/install.js
2923 error npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
2923 error npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
2923 error npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
2923 error npm ERR!     at require (internal/modules/cjs/helpers.js:92:18)
2923 error npm ERR!     at Object.<anonymous> (/Users/riovo/.npm/_cacache/tmp/git-cloneMLx5LV/scripts/install.js:7:13)
2923 error npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2923 error npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2923 error npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
2923 error npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
2923 error npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
2923 error npm ERR!   code: 'MODULE_NOT_FOUND',
2923 error npm ERR!   requireStack: [
2923 error npm ERR!     '/Users/riovo/.npm/_cacache/tmp/git-cloneMLx5LV/scripts/install.js'
2923 error npm ERR!   ]
2923 error npm ERR! }
2923 error
2923 error npm ERR! A complete log of this run can be found in:
2923 error npm ERR!     /Users/riovo/.npm/_logs/2022-09-02T17_36_40_468Z-debug-0.log
2924 verbose exit 1
2925 timing npm Completed in 74509ms
2926 verbose unfinished npm timer reify 1662140194098
2927 verbose unfinished npm timer reify:loadTrees 1662140194109
2928 verbose code 1
2929 error A complete log of this run can be found in:
2929 error     /Users/riovo/.npm/_logs/2022-09-02T17_36_33_979Z-debug-0.log

**Comment by jairo-bc** [comment]
@iovoz Looks like, there is a bug for latest npm (8) version. Do you mind to downgrade it to npm 6 as it is default in node 14?
